language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run test:e2e
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: develop
  github_token:
    secure: t0W3JyvjYf3leHvO5XWgZm9VsKtWvE7Y1oBN4UBMCLJbzYJ3sGSFUNXAMyclhxnDK0mBTd+LElu0NFPK4/QEzXrABtSE8I3X3MrdaJZ0E5Ov7Gj5kw1dncGsabgJVmZsCaRZfW5DFne3+KzPS0oWXHc2y/+20YVf0xHBdbsfi8wrgb0Fb6+qdVr1VIsHgww9Kd17s393G9ZLCtF1DseXBf/iEk6sRYeD4du0e6HOQe2pHQNtDU9Q2X7Ih6qpSkVWQZqDdWmpdCGcnohz454Eab7Fdav0q0y+hYiiZKob4FBGQTKU1KJLeEmeUTMVr1gBXvOBIRcRTUhtnPigOJEwMqjoSpOJhfQ41qEGLADhAtEfcumYRCJCoNDBZCxoM1nENGH25AyE7ybzoMIDxbowZka7pa3Fsm2VOyAsTlhgoKLxdVeye69Zt/5kF563pC54G1jUWVQE4O1O1XeLXM1KZeAfLaTum9N1S3hLrD/IgqkXzFmJR+vymblv9GmqQsr/VyEtdSaS2fAh/A6ZWBEnTO8vpfpoyjomDWW03QJeW24n5cUEGMtFrDiQGIcYNHL7qZ5lMWs1HU4H5Fu9Jb39BLdQkn4a1eeZPmn7D0KzGXfQMqQOx98BtCeJ79U0+vwnqFrnga299KCyu2Z78QAqcmcpwp2wZeQ4DkbM7cLRwmM=